export const config = {
  databaseUrl: process.env.DATABASE_URL || 'postgres://postgres:postgres@localhost:5432/todo_bot',
  geminiApiKey: process.env.GEMINI_API_KEY || '',
  geminiModel: process.env.GEMINI_MODEL || 'gemini-3.1-flash-lite',
  geminiThinkingLevel: process.env.GEMINI_THINKING_LEVEL || 'MEDIUM',
  defaultTimezone: process.env.TIMEZONE || 'Asia/Jakarta',
  defaultReminderLeadMinutes: parseInt(process.env.DEFAULT_REMINDER_LEAD_MINUTES || '30', 10),
  authDir: process.env.AUTH_DIR || './auth_info',
  logLevel: process.env.LOG_LEVEL || 'info',
  antigravityBridgeUrl: process.env.ANTIGRAVITY_BRIDGE_URL || '',
  storageDriver: (process.env.STORAGE_DRIVER || 'local') as 'local' | 's3',
  s3Endpoint: process.env.S3_ENDPOINT || 'http://rust-s3:9000',
  s3Bucket: process.env.S3_BUCKET || 'todo-attachments',
  s3AccessKey: process.env.S3_ACCESS_KEY || '',
  s3SecretKey: process.env.S3_SECRET_KEY || '',
  s3Region: process.env.S3_REGION || 'us-east-1',
  s3ForcePathStyle: process.env.S3_FORCE_PATH_STYLE !== 'false',
  dashboardEnabled: process.env.DASHBOARD_ENABLED === 'true',
  dashboardHost: process.env.DASHBOARD_HOST || '127.0.0.1',
  dashboardPort: parseInt(process.env.DASHBOARD_PORT || '3080', 10),
  dashboardUsername: process.env.DASHBOARD_USERNAME || '',
  dashboardPassword: process.env.DASHBOARD_PASSWORD || '',
  telemetryFlushIntervalMs: Math.max(10_000, parseInt(process.env.TELEMETRY_FLUSH_INTERVAL_MS || '60000', 10)),
};
